## masiv

Итак, массив — это структура данных, в которой:

- Элементы хранятся в указанном порядке.

- Каждый элемент можно получить по индексу за одинаковое время.

- Все элементы приведены к одному и тому же типу данных.

- Максимальное число элементов и объём выделенной памяти заданы заранее.

**Размерностью массива** называют то число индексов, которое необходимо для однозначного получения элемента из массива.

- Соответственно, чтобы найти элемент в массиве размерности 1 (строка из чисел) достаточно одного индекса.

- В двумерном массиве (таблице из чисел) потребуется уже два индекса: номер строки и номер столбца.

- Для трёхмерного массива (например, контейнеры на судне расположены по длине, ширине и высоте судна) потребуется уже три индекса.

In [2]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, ])
print(arr)
print()
print(type(arr))

[0 1 2 3 4]

<class 'numpy.ndarray'>


создадим 2х мерный масив

In [3]:
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

Мы только что узнали, что массив — это набор однотипных данных, но не указали никакой тип. Какого типа данные хранятся теперь в массиве arr? Узнать это можно, напечатав свойство **dtype**:

In [4]:
arr.dtype


dtype('int32')

 Задать тип данных сразу при создании массива можно с помощью параметра dtype:

In [5]:
arr = np.array([1, 5, 2, 9, 10], dtype=np.int8)
print(arr)
arr

[ 1  5  2  9 10]


array([ 1,  5,  2,  9, 10], dtype=int8)

Поменять тип данных во всём массиве можно с помощью тех же функций, которыми мы пользовались для преобразования типов отдельных переменных в предыдущем юните (например, np.int32 или np.float128):

In [6]:
arr = np.float16(arr)
arr

array([ 1.,  5.,  2.,  9., 10.], dtype=float16)

## Функции massiva
обьявим 2 масива одноразмерный и двухразмерный

In [7]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)
print(arr.itemsize)
nd_arr.itemsize

1


2

Узнать размерность массива можно с помощью **.ndim**:

In [8]:
print(arr.ndim)
nd_arr.ndim

1


2

Узнать общее число элементов в массиве можно с помощью **.size**:

In [9]:
print(arr.size)
nd_arr.size

5


9

Форма или структура массива хранится в атрибуте **.shape**:

In [10]:
print(arr.shape)
nd_arr.shape

(5,)


(3, 3)

Наконец, узнать, сколько «весит» каждый элемент массива в байтах позволяет **.itemsize**:

In [11]:
print(arr.itemsize)
nd_arr.itemsize

1


2

Создадим одномерный массив из пяти элементов **np.zeroz**:

In [12]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

Создадим трёхмерный массив с формой 5x4x3 и типом float32:

In [13]:
zeros_3d = np.zeros((3, 4, 5), dtype=np.float32)
print(zeros_3d)
print(zeros_3d.shape)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
(3, 4, 5)


**np.arange()**

In [14]:
np.arange(2.5, 5 , 0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

**np.linspace()**
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

- start и stop являются обязательными параметрами, задающими начало и конец возвращаемого диапазона;
- num — параметр, задающий число элементов, которое должно оказаться в массиве (по умолчанию 50);
- endpoint — включён или исключён конец диапазона (по умолчанию включён);
- retstep (по умолчанию False) позволяет указать, возвращать ли использованный шаг между значениями, помимо самого массива;
- dtype — уже хорошо знакомый нам параметр, задающий тип данных (если не задан, определяется автоматически).

In [16]:
arr, step = np.linspace(-6, 21, 60, False , True, dtype=np.float16)
#print(arr)
print(arr)

[-6.   -5.55 -5.1  -4.65 -4.2  -3.75 -3.3  -2.85 -2.4  -1.95 -1.5  -1.05
 -0.6  -0.15  0.3   0.75  1.2   1.65  2.1   2.55  3.    3.45  3.9   4.35
  4.8   5.25  5.7   6.15  6.6   7.05  7.5   7.95  8.4   8.85  9.3   9.75
 10.2  10.65 11.1  11.55 12.   12.45 12.9  13.35 13.8  14.25 14.7  15.15
 15.6  16.05 16.5  16.95 17.4  17.84 18.3  18.75 19.2  19.66 20.1  20.55]


In [6]:
import numpy as np
def get_unique_loto(num):
    result = np.random.choice(101, size=(num, 5, 5),replace=False)
    return result
print(get_unique_loto(3))


ValueError: Cannot take a larger sample than population when 'replace=False'

In [7]:
import numpy as np
def get_unique_loto(num):
    simple = np.arange(1,101)
    lister = list()
    for i in range(num):
        lister.append(np.random.choice(simple,size=(5, 5), replace=False))
    result = np.array(lister)
    return result

print(get_unique_loto(4))

[[[ 2 42 27 23 45]
  [ 1 63 70 19 66]
  [86 80 24 98 41]
  [55 77 47 94 65]
  [44 56 76 36 73]]

 [[64 38 10 97 32]
  [ 7 52 11 83 47]
  [19 51 50  1 91]
  [36 18 41 81  6]
  [12 49 26 33  3]]

 [[89 52 91 19 77]
  [ 8 40 14 83 16]
  [50 74 21 45 43]
  [69 84 22 28 97]
  [39 99 34 71 96]]

 [[54 43  8 21 28]
  [33 70 69 18 23]
  [ 5 79 31 27 76]
  [87 11 82 60 80]
  [44 19 72 46 58]]]
