## Действия с массивами

In [2]:
import numpy as np
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

Поменять форму массива arr можно с помощью присвоения атрибуту shape кортежа с желаемой формой:

In [3]:
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### **.reshape**

In [4]:
arr = np.arange(8)
new_arr = arr.reshape((2, 4))
new_arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

У функции reshape есть дополнительный именованный аргумент order. Он задаёт принцип, по которому элементы заполняют массив новой формы. Если order='C' (по умолчанию), массив заполняется по строкам, как в примере выше. Если order='F', массив заполняется числами по столбцам:

In [5]:
arr = np.arange(8)
new_arr = arr.reshape((2, 4), order='F')
new_arr

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

### **.transpose**

Ещё одной часто используемой операцией с формой массива (особенно двумерного) является транспонирование. Эта операция меняет строки и столбцы массива местами. В NumPy эту операцию совершает функция transpose.

In [6]:
arr_trans = new_arr.transpose()
arr_trans

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

### Индексация массива

In [7]:
nd_arrey = np.linspace(0, 6, 12, endpoint=False).reshape(3, 4)
nd_arrey

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [8]:
print(nd_arrey[1][2])
print(nd_arrey[1, 2])
print(nd_arrey[:, :2])

3.0
3.0
[[0.  0.5]
 [2.  2.5]
 [4.  4.5]]


### работа с пропущеными даными

In [9]:
data = np.array([4, 9, -5 , 3])
roots = np.sqrt(data)
roots

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_114436\365265803.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

Можно заполнить пропущенные значения, например, нулями. Для этого с помощью функции **np.isnan**(<массив>) узнаем, на каких местах в массиве находятся «не числа»:

In [10]:
np.isnan(roots)

array([False, False,  True, False])

Можно использовать полученный массив из True и False для извлечения элементов из массива roots, на месте которых в булевом массиве указано True. Таким способом можно узнать сами элементы, которые удовлетворяют условию np.isnan:

In [14]:
roots[np.isnan(roots)] = 0
roots
sum(roots)

6.732050807568877