Самой «базовой» функцией в нём можно считать функцию **.rand**. По умолчанию она генерирует число с плавающей точкой между 0 (включительно) и 1 (не включительно):

In [3]:
import numpy as np
print(np.random.rand(5))
print(np.random.rand(2,5) * 100)

[0.91272803 0.2692693  0.5987656  0.02328261 0.27549333]
[[63.17747709  6.40717693 78.78475658 79.62086881 89.14684707]
 [10.1440809  99.62065606 36.78923896 48.18766667 92.25916171]]


Возможно, именно функция **sample** покажется вам удобнее, поскольку информацию о форме массива обычно удобнее хранить в коде в виде кортежа и не задумываться потом о его распаковке. В остальном функция **sample** не отличается от **rand**.

In [5]:
a = (2, 3)
np.random.sample(a)

array([[0.98892236, 0.80981393, 0.81596797],
       [0.31671784, 0.14789588, 0.33617699]])

Первые два аргумента — нижняя и верхняя границы диапазона в формате float, третий опциональный аргумент — форма массива (если не задан, возвращается одно число). Форма массива задаётся кортежем или одним числом.

np.random.uniform(low=0.0, high=1.0, size=None)

In [13]:
np.random.uniform(10, 21, size=(5, 5) )

array([[17.6311459 , 16.11952839, 18.99282121, 18.5807429 , 15.6685196 ],
       [14.25464639, 14.70012041, 20.98800732, 12.7360949 , 20.54591966],
       [20.14947916, 11.33312164, 10.13079633, 19.285158  , 12.00396371],
       [16.62274142, 19.34361582, 18.3360975 , 16.78661645, 17.29261798],
       [12.29737814, 17.41602245, 16.45868335, 12.28278099, 15.36373814]])

ГЕНЕРАЦИЯ INT

np.random.randint(low, high=None, size=None, dtype=int)

In [20]:
np.random.randint(1, 9, size=(5, 5), dtype=np.int16)

array([[8, 3, 4, 4, 2],
       [4, 6, 1, 1, 5],
       [6, 4, 2, 7, 8],
       [3, 6, 5, 6, 5],
       [5, 1, 7, 1, 1]], dtype=int16)

Функцию randint нельзя запустить совсем без параметров, необходимо указать хотя бы одно число.

- Если указан только аргумент low, числа будут генерироваться от 0 до low-1, то есть верхняя граница не включается.
- Если задать low и high, числа будут генерироваться от low (включительно) до high (не включительно).
- size задаёт форму массива уже привычным для вас образом: одним числом — для одномерного или кортежем — для многомерного.
- dtype позволяет задать конкретный тип данных, который должен быть использован в массиве.

Просто перемешать все числа в массиве позволяет функция **np.random.shuffle**.

In [24]:
arr = np.arange(6)
print(arr)
print(np.random.shuffle(arr))
arr

[0 1 2 3 4 5]
None


array([1, 4, 5, 0, 2, 3])

чтобы создать новый перемешеный масив **np.random.permutation()**

In [39]:
arr = np.arange(6)
new_arr = np.random.permutation(arr)
print(new_arr)
play_list = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
new_play_list = np.random.permutation(play_list)
print(new_play_list)

[3 0 4 1 5 2]
['ACDC' 'Pink Floyd' 'Deep Purple' 'The Beatles']


Перемешать набор чисел от 0 до n-1 можно с помощью записи **np.random.permutation(n)**, где n — верхняя граница, которая бы использовалась для генерации набора чисел функцией arange.

In [42]:
np.random.permutation(10)

array([7, 5, 1, 4, 8, 2, 3, 0, 6, 9])

Чтобы получить случайный набор объектов из массива, используется функция **np.random.choice**:

choice(a, size=None, replace=True)
- a — одномерный массив или число для генерации arange(a);
- size — желаемая форма массива (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);
- replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).

In [49]:
print(np.random.choice(play_list, size=(2,3), replace=True))

[['Pink Floyd' 'Deep Purple' 'ACDC']
 ['ACDC' 'ACDC' 'The Beatles']]


### **SEED** 

Самостоятельно задать seed в NumPy можно с помощью функции **np.random.seed**(<np.uint32>). Число в скобках должно быть в пределах от 0 до 2**32 - 1 (=4294967295).

In [56]:
np.random.seed(100)
print(np.random.randint(10, size=(3)))
print(np.random.randint(10, size=(3)))
print(np.random.randint(10, size=(3)))

[8 8 3]
[7 7 0]
[4 2 5]
