## **Vector**
база функций:https://pyprog.pro/statistics_functions/statistics_function.html
В программировании вектором называют одномерный проиндексированный набор данных, другими словами — одномерный массив.

In [1]:
import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
print(vec1 + vec2)
print(vec1 * vec2)

print(vec2 * 10)
print(vec1 < vec2)

[14.  10.  10.6 15.5]
[24.  24.  25.2 32.5]
[120.  60.  36. 130.]
[ True  True False  True]


Посчитаем длину вектора

In [2]:
vec = np.array([3, 4]) 

lenght = np.sqrt(np.sum(vec ** 2))
print(lenght)

5.0


Но можно было поступить проще. В NumPy есть специальный подмодуль **.linalg**, который позволяет производить операции из линейной алгебры.

Для вычисления длины вектора нам потребуется функция **.norm**:

In [3]:
lenght = np.linalg.norm(vec)

Растояние между векторами
Реализуем вычисление расстояния в коде. Сначала — «сложным» способом напрямую из формулы:

In [4]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
print(distance)
print(np.linalg.norm(vec1 - vec2))

12.206555615733702
12.206555615733702


**скалярным произведением** двух векторов называют сумму произведений их соответствующих координат.

**.dot** - встроеная в нампи функция по находению сколярного произведенния

In [5]:
vec1 = np.arange(1,6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
print(scalar_product)
print(np.dot(vec1, vec2))

250.0
250.0


Скалярное произведение также имеет широкое применение в математике и других операциях с векторами. В частности, равенство скалярного произведения **нулю** означает **перпендикулярность** рассматриваемых векторов:

In [6]:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)

0

ункции np.min и np.max позволяют находить максимальное и минимальное значение в векторе. Их можно записывать как в виде **np.min(<vector>)**, так и в виде **<vector>.min()**:

In [7]:
vec = np.array([2,7,18,28,18,1,8,4])
print(vec.min())
print(np.min(vec))
print(vec.max())
print(np.max(vec))

1
1
28
28


Функция **mean** позволяет посчитать среднее статистическое значение. Больше не требуется реализовывать её «руками»!

In [8]:
print(vec.mean())
print(np.mean(vec))

10.75
10.75


In [9]:
# Введите свое решение ниже
import numpy as np
def min_max_dist(*vectors):
    line = list()
    lens = len(vectors)
    vector =vectors[0]
    for i in range(1, lens):
        line.append(np.linalg.norm(vector - vectors[i]))
        vector = vectors[i]
    min_dist = min(line)
    max_dist = max(line)
    return min_dist , max_dist
        


vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

min_max_dist(vec1, vec2, vec3)
# (5.196152422706632, 10.392304845413264)



(5.196152422706632, 5.196152422706632)